// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAsset = "assets"

// Asset mapped from table <assets>
type Asset struct {
	ID             int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	AssetSetID     int64  `gorm:"column:asset_set_id;type:bigint;not null" json:"asset_set_id"`
	AssetID        int64  `gorm:"column:asset_id;type:bigint;not null" json:"asset_id"`
	AssetVersionID int64  `gorm:"column:asset_version_id;type:bigint;not null" json:"asset_version_id"`
	AssetName      string `gorm:"column:asset_name;type:character varying(50);not null" json:"asset_name"`
	CreatorName    string `gorm:"column:creator_name;type:character varying(50);not null" json:"creator_name"`
}

// TableName Asset's table name
func (*Asset) TableName() string {
	return TableNameAsset
}
