// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAssetSet = "asset_sets"

// AssetSet mapped from table <asset_sets>
type AssetSet struct {
	ID                int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	Name              string `gorm:"column:name;type:character varying(100);not null" json:"name"`
	Description       string `gorm:"column:description;type:character varying(1000);not null" json:"description"`
	ImageAssetID      int64  `gorm:"column:image_asset_id;type:bigint;not null" json:"image_asset_id"`
	ImageAssetUpdated int64  `gorm:"column:image_asset_updated;type:bigint;not null" json:"image_asset_updated"`
	CreatorName       string `gorm:"column:creator_name;type:character varying(50);not null" json:"creator_name"`
	CreatorID         int64  `gorm:"column:creator_id;type:bigint;not null" json:"creator_id"`
	SubscriberCount   *int64 `gorm:"column:subscriber_count;type:bigint" json:"subscriber_count"`
}

// TableName AssetSet's table name
func (*AssetSet) TableName() string {
	return TableNameAssetSet
}
