// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSubscriber = "subscribers"

// Subscriber mapped from table <subscribers>
type Subscriber struct {
	ID         int64 `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	UserID     int64 `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	AssetSetID int64 `gorm:"column:asset_set_id;type:bigint;not null" json:"asset_set_id"`
}

// TableName Subscriber's table name
func (*Subscriber) TableName() string {
	return TableNameSubscriber
}
