// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID       int64  `gorm:"column:id;type:bigint;primaryKey" json:"id"`
	UserName string `gorm:"column:user_name;type:character varying(50);not null" json:"user_name"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
