// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"orisrightpaw/roblox-set-archive/internal/dal/model"
)

func newAssetSet(db *gorm.DB, opts ...gen.DOOption) assetSet {
	_assetSet := assetSet{}

	_assetSet.assetSetDo.UseDB(db, opts...)
	_assetSet.assetSetDo.UseModel(&model.AssetSet{})

	tableName := _assetSet.assetSetDo.TableName()
	_assetSet.ALL = field.NewAsterisk(tableName)
	_assetSet.ID = field.NewInt64(tableName, "id")
	_assetSet.Name = field.NewString(tableName, "name")
	_assetSet.Description = field.NewString(tableName, "description")
	_assetSet.ImageAssetID = field.NewInt64(tableName, "image_asset_id")
	_assetSet.ImageAssetUpdated = field.NewInt64(tableName, "image_asset_updated")
	_assetSet.CreatorName = field.NewString(tableName, "creator_name")
	_assetSet.CreatorID = field.NewInt64(tableName, "creator_id")
	_assetSet.SubscriberCount = field.NewInt64(tableName, "subscriber_count")

	_assetSet.fillFieldMap()

	return _assetSet
}

type assetSet struct {
	assetSetDo assetSetDo

	ALL               field.Asterisk
	ID                field.Int64
	Name              field.String
	Description       field.String
	ImageAssetID      field.Int64
	ImageAssetUpdated field.Int64
	CreatorName       field.String
	CreatorID         field.Int64
	SubscriberCount   field.Int64

	fieldMap map[string]field.Expr
}

func (a assetSet) Table(newTableName string) *assetSet {
	a.assetSetDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a assetSet) As(alias string) *assetSet {
	a.assetSetDo.DO = *(a.assetSetDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *assetSet) updateTableName(table string) *assetSet {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.Name = field.NewString(table, "name")
	a.Description = field.NewString(table, "description")
	a.ImageAssetID = field.NewInt64(table, "image_asset_id")
	a.ImageAssetUpdated = field.NewInt64(table, "image_asset_updated")
	a.CreatorName = field.NewString(table, "creator_name")
	a.CreatorID = field.NewInt64(table, "creator_id")
	a.SubscriberCount = field.NewInt64(table, "subscriber_count")

	a.fillFieldMap()

	return a
}

func (a *assetSet) WithContext(ctx context.Context) IAssetSetDo { return a.assetSetDo.WithContext(ctx) }

func (a assetSet) TableName() string { return a.assetSetDo.TableName() }

func (a assetSet) Alias() string { return a.assetSetDo.Alias() }

func (a assetSet) Columns(cols ...field.Expr) gen.Columns { return a.assetSetDo.Columns(cols...) }

func (a *assetSet) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *assetSet) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["id"] = a.ID
	a.fieldMap["name"] = a.Name
	a.fieldMap["description"] = a.Description
	a.fieldMap["image_asset_id"] = a.ImageAssetID
	a.fieldMap["image_asset_updated"] = a.ImageAssetUpdated
	a.fieldMap["creator_name"] = a.CreatorName
	a.fieldMap["creator_id"] = a.CreatorID
	a.fieldMap["subscriber_count"] = a.SubscriberCount
}

func (a assetSet) clone(db *gorm.DB) assetSet {
	a.assetSetDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a assetSet) replaceDB(db *gorm.DB) assetSet {
	a.assetSetDo.ReplaceDB(db)
	return a
}

type assetSetDo struct{ gen.DO }

type IAssetSetDo interface {
	gen.SubQuery
	Debug() IAssetSetDo
	WithContext(ctx context.Context) IAssetSetDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAssetSetDo
	WriteDB() IAssetSetDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAssetSetDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAssetSetDo
	Not(conds ...gen.Condition) IAssetSetDo
	Or(conds ...gen.Condition) IAssetSetDo
	Select(conds ...field.Expr) IAssetSetDo
	Where(conds ...gen.Condition) IAssetSetDo
	Order(conds ...field.Expr) IAssetSetDo
	Distinct(cols ...field.Expr) IAssetSetDo
	Omit(cols ...field.Expr) IAssetSetDo
	Join(table schema.Tabler, on ...field.Expr) IAssetSetDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAssetSetDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAssetSetDo
	Group(cols ...field.Expr) IAssetSetDo
	Having(conds ...gen.Condition) IAssetSetDo
	Limit(limit int) IAssetSetDo
	Offset(offset int) IAssetSetDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAssetSetDo
	Unscoped() IAssetSetDo
	Create(values ...*model.AssetSet) error
	CreateInBatches(values []*model.AssetSet, batchSize int) error
	Save(values ...*model.AssetSet) error
	First() (*model.AssetSet, error)
	Take() (*model.AssetSet, error)
	Last() (*model.AssetSet, error)
	Find() ([]*model.AssetSet, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AssetSet, err error)
	FindInBatches(result *[]*model.AssetSet, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.AssetSet) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAssetSetDo
	Assign(attrs ...field.AssignExpr) IAssetSetDo
	Joins(fields ...field.RelationField) IAssetSetDo
	Preload(fields ...field.RelationField) IAssetSetDo
	FirstOrInit() (*model.AssetSet, error)
	FirstOrCreate() (*model.AssetSet, error)
	FindByPage(offset int, limit int) (result []*model.AssetSet, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAssetSetDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a assetSetDo) Debug() IAssetSetDo {
	return a.withDO(a.DO.Debug())
}

func (a assetSetDo) WithContext(ctx context.Context) IAssetSetDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a assetSetDo) ReadDB() IAssetSetDo {
	return a.Clauses(dbresolver.Read)
}

func (a assetSetDo) WriteDB() IAssetSetDo {
	return a.Clauses(dbresolver.Write)
}

func (a assetSetDo) Session(config *gorm.Session) IAssetSetDo {
	return a.withDO(a.DO.Session(config))
}

func (a assetSetDo) Clauses(conds ...clause.Expression) IAssetSetDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a assetSetDo) Returning(value interface{}, columns ...string) IAssetSetDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a assetSetDo) Not(conds ...gen.Condition) IAssetSetDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a assetSetDo) Or(conds ...gen.Condition) IAssetSetDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a assetSetDo) Select(conds ...field.Expr) IAssetSetDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a assetSetDo) Where(conds ...gen.Condition) IAssetSetDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a assetSetDo) Order(conds ...field.Expr) IAssetSetDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a assetSetDo) Distinct(cols ...field.Expr) IAssetSetDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a assetSetDo) Omit(cols ...field.Expr) IAssetSetDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a assetSetDo) Join(table schema.Tabler, on ...field.Expr) IAssetSetDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a assetSetDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAssetSetDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a assetSetDo) RightJoin(table schema.Tabler, on ...field.Expr) IAssetSetDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a assetSetDo) Group(cols ...field.Expr) IAssetSetDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a assetSetDo) Having(conds ...gen.Condition) IAssetSetDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a assetSetDo) Limit(limit int) IAssetSetDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a assetSetDo) Offset(offset int) IAssetSetDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a assetSetDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAssetSetDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a assetSetDo) Unscoped() IAssetSetDo {
	return a.withDO(a.DO.Unscoped())
}

func (a assetSetDo) Create(values ...*model.AssetSet) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a assetSetDo) CreateInBatches(values []*model.AssetSet, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a assetSetDo) Save(values ...*model.AssetSet) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a assetSetDo) First() (*model.AssetSet, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetSet), nil
	}
}

func (a assetSetDo) Take() (*model.AssetSet, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetSet), nil
	}
}

func (a assetSetDo) Last() (*model.AssetSet, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetSet), nil
	}
}

func (a assetSetDo) Find() ([]*model.AssetSet, error) {
	result, err := a.DO.Find()
	return result.([]*model.AssetSet), err
}

func (a assetSetDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AssetSet, err error) {
	buf := make([]*model.AssetSet, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a assetSetDo) FindInBatches(result *[]*model.AssetSet, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a assetSetDo) Attrs(attrs ...field.AssignExpr) IAssetSetDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a assetSetDo) Assign(attrs ...field.AssignExpr) IAssetSetDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a assetSetDo) Joins(fields ...field.RelationField) IAssetSetDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a assetSetDo) Preload(fields ...field.RelationField) IAssetSetDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a assetSetDo) FirstOrInit() (*model.AssetSet, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetSet), nil
	}
}

func (a assetSetDo) FirstOrCreate() (*model.AssetSet, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AssetSet), nil
	}
}

func (a assetSetDo) FindByPage(offset int, limit int) (result []*model.AssetSet, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a assetSetDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a assetSetDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a assetSetDo) Delete(models ...*model.AssetSet) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *assetSetDo) withDO(do gen.Dao) *assetSetDo {
	a.DO = *do.(*gen.DO)
	return a
}
